# Generated by Django 5.1.3 on 2024-11-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='licence_number',
            new_name='license_number',
        ),
    ]
